import pool from "../config/db.js";

async function runMigration() {
  const client = await pool.connect();
  try {
    await client.query("BEGIN");

    await client.query(`
      CREATE TABLE IF NOT EXISTS partner_employee_approval_requests (
        approval_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
        admin_id BIGINT REFERENCES users(user_id),
        submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        reviewed_at TIMESTAMP,
        approval_status VARCHAR(30) NOT NULL CONSTRAINT chk_pear_approval_status CHECK (approval_status IN ('PENDING', 'APPROVED', 'REJECTED')),
        admin_feedback TEXT
      );
    `);

    await client.query(`
      CREATE INDEX IF NOT EXISTS idx_pear_user_id ON partner_employee_approval_requests(user_id);
    `);

    // Kiểm tra và seed dữ liệu cho các nhân viên có sẵn (user 6, 7) nếu chưa có
    const check6 = await client.query(
      "SELECT approval_request_id FROM partner_employee_approval_requests WHERE user_id = 6"
    );
    if (check6.rows.length === 0) {
      await client.query(`
        INSERT INTO partner_employee_approval_requests (user_id, admin_id, submitted_at, reviewed_at, approval_status)
        VALUES (6, 1, '2026-01-03 10:30:00', '2026-01-03 11:00:00', 'APPROVED')
      `);
    }

    const check7 = await client.query(
      "SELECT approval_request_id FROM partner_employee_approval_requests WHERE user_id = 7"
    );
    if (check7.rows.length === 0) {
      await client.query(`
        INSERT INTO partner_employee_approval_requests (user_id, admin_id, submitted_at, reviewed_at, approval_status)
        VALUES (7, 1, '2026-01-03 11:00:00', '2026-01-03 11:30:00', 'APPROVED')
      `);
    }

    // Thêm 2 nhân viên mẫu chờ duyệt (PENDING) để test giao diện
    const testEmp1 = await client.query(
      "SELECT user_id FROM users WHERE email = 'employee_test_pending1@voucher.vn'"
    );
    if (testEmp1.rows.length === 0) {
      const uRes1 = await client.query(`
        INSERT INTO users (full_name, email, phone, password_hash, role, gender, identity_no, nationality, status, created_at)
        VALUES ('Phạm Minh Quân', 'employee_test_pending1@voucher.vn', '0903000091', '$2b$10$mhm5mMiiPXKJx8JrARS/wemVunACuQI2Ug6ezweTw2jB8Z2fQ92zW', 'PARTNER_EMPLOYEE', 'MALE', '001095000091', 'Việt Nam', 'ACTIVE', CURRENT_TIMESTAMP - INTERVAL '2 hours')
        RETURNING user_id
      `);
      const uid1 = uRes1.rows[0].user_id;
      await client.query(`INSERT INTO partner_employees (user_id, branch_id) VALUES ($1, 1)`, [uid1]);
      await client.query(`
        INSERT INTO partner_employee_approval_requests (user_id, submitted_at, approval_status)
        VALUES ($1, CURRENT_TIMESTAMP - INTERVAL '2 hours', 'PENDING')
      `, [uid1]);
    }

    const testEmp2 = await client.query(
      "SELECT user_id FROM users WHERE email = 'employee_test_pending2@voucher.vn'"
    );
    if (testEmp2.rows.length === 0) {
      const uRes2 = await client.query(`
        INSERT INTO users (full_name, email, phone, password_hash, role, gender, identity_no, nationality, status, created_at)
        VALUES ('Trần Ngọc Linh', 'employee_test_pending2@voucher.vn', '0903000092', '$2b$10$mhm5mMiiPXKJx8JrARS/wemVunACuQI2Ug6ezweTw2jB8Z2fQ92zW', 'PARTNER_EMPLOYEE', 'FEMALE', '001196000092', 'Việt Nam', 'ACTIVE', CURRENT_TIMESTAMP - INTERVAL '5 hours')
        RETURNING user_id
      `);
      const uid2 = uRes2.rows[0].user_id;
      await client.query(`INSERT INTO partner_employees (user_id, branch_id) VALUES ($1, 3)`, [uid2]);
      await client.query(`
        INSERT INTO partner_employee_approval_requests (user_id, submitted_at, approval_status)
        VALUES ($1, CURRENT_TIMESTAMP - INTERVAL '5 hours', 'PENDING')
      `, [uid2]);
    }

    await client.query("COMMIT");
    console.log("Migration partner_employee_approval_requests completed successfully.");
  } catch (err) {
    await client.query("ROLLBACK");
    console.error("Migration failed:", err);
  } finally {
    client.release();
    await pool.end();
  }
}

runMigration();
