import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "border": "#e2e8f0",
        "ring": "#004ac6",
        "text-main": "#191b23",
        "text-muted": "#64748b",
        "primary": "#004ac6",
        "inverse-on-surface": "#f0f0fb",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#005236",
        "tertiary-amber": "#F59E0B",
        "primary-fixed": "#dbe1ff",
        "surface-container-highest": "#e1e2ed",
        "surface-tint": "#0053db",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-container-low": "#f3f3fe",
        "secondary-container": "#6cf8bb",
        "on-tertiary-container": "#ffeedd",
        "surface-container": "#ededf9",
        "surface-bright": "#faf8ff",
        "on-primary-container": "#eeefff",
        "tertiary-container": "#996100",
        "secondary": "#006c49",
        "muted-slate": "#94A3B8",
        "on-tertiary-fixed": "#2a1700",
        "primary-fixed-dim": "#b4c5ff",
        "inverse-primary": "#b4c5ff",
        "outline": "#737686",
        "on-primary": "#ffffff",
        "on-surface": "#191b23",
        "primary-container": "#2563eb",
        "on-primary-fixed-variant": "#003ea8",
        "on-surface-variant": "#434655",
        "on-tertiary": "#ffffff",
        "tertiary": "#784b00",
        "tertiary-fixed-dim": "#ffb95f",
        "tertiary-fixed": "#ffddb8",
        "secondary-fixed": "#6ffbbe",
        "on-primary-fixed": "#00174b",
        "on-error": "#ffffff",
        "surface-dim": "#F7F9FB",
        "outline-variant": "#c3c6d7",
        "surface-variant": "#e1e2ed",
        "surface-container-high": "#e7e7f3",
        "surface": "#faf8ff",
        "on-background": "#191b23",
        "secondary-fixed-dim": "#4edea3",
        "error-container": "#ffdad6",
        "error-red": "#BA1A1A",
        "inverse-surface": "#2e3039",
        "on-secondary-container": "#00714d",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "surface-lowest": "#ffffff",
        "background": "#faf8ff"
      },
      fontSize: {
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-xl-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-lg": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sidebar-width": "280px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "base": "8px",
        "margin-desktop": "48px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      boxShadow: {
        "2xs": "0 1px rgb(0 0 0 / 0.05)",
        "xs": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      },
      backdropBlur: {
        "xs": "2px",
      },
      keyframes: {
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        shimmer: {
          "100%": { transform: "translateX(100%)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-5px)" },
        },
        gradientMove: {
          "0%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
          "100%": { backgroundPosition: "0% 50%" },
        },
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        scaleUp: {
          from: { opacity: "0", transform: "scale(0.95)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        slideDown: {
          from: { opacity: "0", transform: "translateY(-0.5rem)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        enter: {
          from: {
            opacity: "var(--tw-enter-opacity, 1)",
            transform: "scale(var(--tw-enter-scale, 1))",
          },
        },
      },
      animation: {
        fadeIn: "fadeIn 150ms ease-out",
        scaleUp: "scaleUp 150ms ease-out",
        slideDown: "slideDown 200ms ease-out",
        in: "enter 150ms ease-out",
        "fade-in-up": "fadeInUp 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "shimmer": "shimmer 2s infinite",
        "float": "float 3s ease-in-out infinite",
        "gradient-move": "gradientMove 8s ease infinite",
      },
    },
  },
  plugins: [],
};
export default config;
