-- PostgreSQL DDL Script for Voucher System
-- Generated strictly based on Database Specification ERD & BRD v1.0

-- Drop existing tables in reverse dependency order
DROP TABLE IF EXISTS system_logs CASCADE;
DROP TABLE IF EXISTS contents CASCADE;
DROP TABLE IF EXISTS popups CASCADE;
DROP TABLE IF EXISTS banners CASCADE;
DROP TABLE IF EXISTS order_cancellations CASCADE;
DROP TABLE IF EXISTS reviews_feedback CASCADE;
DROP TABLE IF EXISTS issued_vouchers CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS voucher_approval_requests CASCADE;
DROP TABLE IF EXISTS voucher_program_images CASCADE;
DROP TABLE IF EXISTS voucher_program_branches CASCADE;
DROP TABLE IF EXISTS voucher_programs CASCADE;
DROP TABLE IF EXISTS partner_employee_approval_requests CASCADE;
DROP TABLE IF EXISTS partner_employees CASCADE;
DROP TABLE IF EXISTS branches CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS partner_approval_requests CASCADE;
DROP TABLE IF EXISTS partners CASCADE;
DROP TABLE IF EXISTS user_locks CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 1. Bảng users (Người dùng)
CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20) UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL CONSTRAINT chk_users_role CHECK (role IN ('CUSTOMER', 'PARTNER', 'ADMIN', 'PARTNER_EMPLOYEE')),
    gender VARCHAR(20) CONSTRAINT chk_users_gender CHECK (gender IS NULL OR gender IN ('MALE', 'FEMALE', 'OTHER')),
    identity_no VARCHAR(30) UNIQUE,                             -- Số CCCD / CMND
    nationality VARCHAR(100),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CONSTRAINT chk_users_status CHECK (status IN ('ACTIVE', 'LOCKED')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMP
);

-- 2. Bảng partners (Đối tác)
CREATE TABLE partners (
    user_id BIGINT PRIMARY KEY REFERENCES users(user_id),
    business_name VARCHAR(255) NOT NULL,
    tax_code VARCHAR(50) NOT NULL UNIQUE,
    activity_status VARCHAR(20) NOT NULL CONSTRAINT chk_partners_activity_status CHECK (activity_status IN ('ACTIVE', 'INACTIVE', 'LOCKED')),
    registered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Thông tin pháp lý
    business_license_no VARCHAR(100),                           -- Số ĐKKD
    license_issue_date DATE,                                    -- Ngày cấp ĐKKD
    license_issue_place VARCHAR(255),                           -- Nơi cấp ĐKKD
    representative_title VARCHAR(100),                          -- Chức danh người đại diện
    brand_logo VARCHAR(500)                                     -- URL ảnh logo thương hiệu
);

-- 2a. Bảng partner_approval_requests (Yêu cầu duyệt đối tác)
CREATE TABLE partner_approval_requests (
    approval_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id BIGINT NOT NULL REFERENCES partners(user_id) ON DELETE CASCADE,
    admin_id BIGINT REFERENCES users(user_id),
    submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMP,
    approval_status VARCHAR(30) NOT NULL CONSTRAINT chk_par_approval_status CHECK (approval_status IN ('PENDING', 'APPROVED', 'REJECTED')),
    admin_feedback TEXT
);

-- 3. Bảng categories (Danh mục)
CREATE TABLE categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(150) NOT NULL UNIQUE,
    description TEXT,
    status VARCHAR(20) NOT NULL CONSTRAINT chk_categories_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- 4. Bảng branches (Chi nhánh)
CREATE TABLE branches (
    branch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id BIGINT NOT NULL REFERENCES partners(user_id),
    branch_name VARCHAR(255) NOT NULL,
    address VARCHAR(500) NOT NULL,
    region VARCHAR(150),
    phone VARCHAR(20),
    status VARCHAR(20) NOT NULL CONSTRAINT chk_branches_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- 5. Bảng partner_employees (Nhân viên đối tác)
CREATE TABLE partner_employees (
    user_id BIGINT PRIMARY KEY REFERENCES users(user_id),
    branch_id BIGINT NOT NULL REFERENCES branches(branch_id)
);

-- 5a. Bảng partner_employee_approval_requests (Yêu cầu duyệt nhân viên đối tác)
CREATE TABLE partner_employee_approval_requests (
    approval_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    admin_id BIGINT REFERENCES users(user_id),
    submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMP,
    approval_status VARCHAR(30) NOT NULL CONSTRAINT chk_pear_approval_status CHECK (approval_status IN ('PENDING', 'APPROVED', 'REJECTED')),
    admin_feedback TEXT
);

-- 6. Bảng voucher_programs (Chương trình voucher)
CREATE TABLE voucher_programs (
    program_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id BIGINT NOT NULL REFERENCES partners(user_id),
    category_id BIGINT NOT NULL REFERENCES categories(category_id),
    program_name VARCHAR(255) NOT NULL,
    original_price DECIMAL(18,2) NOT NULL CONSTRAINT chk_vp_original_price CHECK (original_price >= 0),
    sale_price DECIMAL(18,2) NOT NULL CONSTRAINT chk_vp_sale_price CHECK (sale_price >= 0),
    discount_amount DECIMAL(18,2) GENERATED ALWAYS AS (original_price - sale_price) STORED,
    issue_quantity INT NOT NULL CONSTRAINT chk_vp_issue_quantity CHECK (issue_quantity > 0),
    sale_start_at TIMESTAMP NOT NULL,
    sale_end_at TIMESTAMP NOT NULL,
    use_start_at TIMESTAMP NOT NULL,
    use_end_at TIMESTAMP NOT NULL,
    display_status VARCHAR(20) NOT NULL CONSTRAINT chk_vp_display_status CHECK (display_status IN ('DRAFT', 'PENDING_APPROVAL', 'PUBLISHED', 'HIDDEN', 'ENDED')),
    CONSTRAINT chk_vp_sale_dates CHECK (sale_end_at > sale_start_at),
    CONSTRAINT chk_vp_use_dates CHECK (use_end_at > use_start_at)
);

-- 7. Bảng voucher_program_branches (Chi nhánh áp dụng chương trình - Bảng trung gian N:N)
CREATE TABLE voucher_program_branches (
    program_id BIGINT NOT NULL REFERENCES voucher_programs(program_id),
    branch_id BIGINT NOT NULL REFERENCES branches(branch_id),
    PRIMARY KEY (program_id, branch_id)
);

-- 7a. Bảng ảnh chương trình voucher (gallery)
CREATE TABLE voucher_program_images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT NOT NULL REFERENCES voucher_programs(program_id) ON DELETE CASCADE,
    image_url VARCHAR(1000) NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INT NOT NULL DEFAULT 0 CONSTRAINT chk_vpi_sort_order CHECK (sort_order >= 0)
);

-- 8. Bảng voucher_approval_requests (Yêu cầu duyệt voucher)
CREATE TABLE voucher_approval_requests (
    approval_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT NOT NULL REFERENCES voucher_programs(program_id),
    admin_id BIGINT REFERENCES users(user_id),
    submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMP,
    approval_status VARCHAR(30) NOT NULL CONSTRAINT chk_var_approval_status CHECK (approval_status IN ('PENDING', 'APPROVED', 'REJECTED')),
    admin_feedback TEXT
);

-- 9. Bảng cart_items (Chi tiết giỏ hàng)
CREATE TABLE cart_items (
    cart_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES users(user_id),
    program_id BIGINT NOT NULL REFERENCES voucher_programs(program_id),
    quantity INT NOT NULL CONSTRAINT chk_cart_items_quantity CHECK (quantity > 0),
    CONSTRAINT uq_cart_items_customer_program UNIQUE (customer_id, program_id)
);

-- 10. Bảng orders (Đơn hàng)
CREATE TABLE orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_user_id BIGINT NOT NULL REFERENCES users(user_id),
    recipient_user_id BIGINT REFERENCES users(user_id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_amount DECIMAL(18,2) NOT NULL CONSTRAINT chk_orders_total_amount CHECK (total_amount >= 0),
    payment_method VARCHAR(50) NOT NULL CONSTRAINT chk_orders_payment_method CHECK (payment_method IN ('VNPAY', 'MOMO', 'CREDIT_CARD', 'BANK_TRANSFER', 'CASH')),
    payment_status VARCHAR(30) NOT NULL CONSTRAINT chk_orders_payment_status CHECK (payment_status IN ('UNPAID', 'PAID', 'FAILED', 'REFUNDED')),
    order_status VARCHAR(30) NOT NULL CONSTRAINT chk_orders_order_status CHECK (order_status IN ('PENDING', 'CANCELLED', 'COMPLETED'))
);

-- 11. Bảng order_items (Chi tiết đơn hàng)
CREATE TABLE order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(order_id),
    program_id BIGINT NOT NULL REFERENCES voucher_programs(program_id),
    quantity INT NOT NULL CONSTRAINT chk_order_items_quantity CHECK (quantity > 0),
    unit_price DECIMAL(18,2) NOT NULL CONSTRAINT chk_order_items_unit_price CHECK (unit_price >= 0),
    line_total DECIMAL(18,2) GENERATED ALWAYS AS (quantity * unit_price) STORED
);

-- 12. Bảng issued_vouchers (Voucher phát hành)
CREATE TABLE issued_vouchers (
    issued_voucher_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT NOT NULL REFERENCES voucher_programs(program_id),
    order_item_id BIGINT NOT NULL REFERENCES order_items(order_item_id),
    owner_user_id BIGINT NOT NULL REFERENCES users(user_id),
    voucher_code VARCHAR(100) NOT NULL UNIQUE,
    qr_code VARCHAR(500),
    usage_status VARCHAR(30) NOT NULL CONSTRAINT chk_iv_usage_status CHECK (usage_status IN ('UNUSED', 'USED', 'EXPIRED', 'CANCELLED')),
    issued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    applicable_region VARCHAR(150),
    used_at TIMESTAMP,
    discount_amount DECIMAL(18,2) CONSTRAINT chk_iv_discount_amount CHECK (discount_amount IS NULL OR discount_amount >= 0)
);

-- 13. Bảng reviews_feedback (Đánh giá phản hồi)
CREATE TABLE reviews_feedback (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issued_voucher_id BIGINT NOT NULL REFERENCES issued_vouchers(issued_voucher_id),
    customer_id BIGINT NOT NULL REFERENCES users(user_id),
    rating SMALLINT CONSTRAINT chk_rf_rating CHECK (rating IS NULL OR (rating >= 1 AND rating <= 5)),
    review_content TEXT,
    complaint_content TEXT,
    submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 14. Bảng order_cancellations (Hủy đơn hàng)
CREATE TABLE order_cancellations (
    cancellation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE REFERENCES orders(order_id),
    admin_id BIGINT REFERENCES users(user_id),
    requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reason TEXT NOT NULL
);

-- 15. Bảng system_logs (Nhật ký hệ thống)
CREATE TABLE system_logs (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    action VARCHAR(100) NOT NULL,
    object_id VARCHAR(100),
    object_type VARCHAR(50) CONSTRAINT chk_sl_object_type CHECK (object_type IS NULL OR object_type IN (
        'USER', 'PARTNER', 'PARTNER_EMPLOYEE', 'BRANCH', 'CATEGORY', 'VOUCHER_PROGRAM',
        'APPROVAL_REQUEST', 'CART_ITEM', 'ORDER', 'ORDER_ITEM',
        'ISSUED_VOUCHER', 'REVIEW_FEEDBACK', 'ORDER_CANCELLATION',
        'BANNER', 'POPUP', 'CONTENT'
    )),
    old_value JSONB,
    new_value JSONB,
    performed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    result VARCHAR(30) NOT NULL CONSTRAINT chk_sl_result CHECK (result IN ('SUCCESS', 'FAILED')),
    CONSTRAINT chk_sl_object_nullity CHECK (
        (object_id IS NULL AND object_type IS NULL) OR
        (object_id IS NOT NULL AND object_type IS NOT NULL)
    )
);

-- 16. Bảng banners (Banner)
CREATE TABLE banners (
    banner_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT NOT NULL REFERENCES voucher_programs(program_id),
    title VARCHAR(255) NOT NULL,
    image_url VARCHAR(1000) NOT NULL,
    target_url VARCHAR(1000),
    display_position VARCHAR(100),
    display_from TIMESTAMP,
    display_to TIMESTAMP,
    status VARCHAR(20) NOT NULL CONSTRAINT chk_banners_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- 17. Bảng popups (Popup)
CREATE TABLE popups (
    popup_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT NOT NULL REFERENCES voucher_programs(program_id),
    title VARCHAR(255) NOT NULL,
    content TEXT,
    target_url VARCHAR(1000),
    image_url VARCHAR(1000),
    start_at TIMESTAMP,
    end_at TIMESTAMP,
    status VARCHAR(20) NOT NULL CONSTRAINT chk_popups_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- 18. Bảng contents (Nội dung)
CREATE TABLE contents (
    content_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT NOT NULL REFERENCES voucher_programs(program_id),
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    content_type VARCHAR(30) NOT NULL CONSTRAINT chk_contents_content_type CHECK (content_type IN ('POLICY', 'ARTICLE', 'PROMOTION', 'GUIDE')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    status VARCHAR(20) NOT NULL CONSTRAINT chk_contents_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);


-- 19. Bảng user_locks (Lý do khóa tài khoản)
CREATE TABLE user_locks (
    user_id BIGINT PRIMARY KEY REFERENCES users(user_id),
    reason TEXT NOT NULL
);

-- INDEXES SECTION
-- Indexes cho tất cả các Khóa ngoại (Foreign Keys)
CREATE INDEX idx_partners_user_id ON partners(user_id);
CREATE INDEX idx_par_partner_id ON partner_approval_requests(partner_id);
CREATE INDEX idx_par_admin_id ON partner_approval_requests(admin_id);
CREATE INDEX idx_branches_partner_id ON branches(partner_id);
CREATE INDEX idx_partner_employees_branch_id ON partner_employees(branch_id);
CREATE INDEX idx_pear_user_id ON partner_employee_approval_requests(user_id);
CREATE INDEX idx_voucher_programs_partner_id ON voucher_programs(partner_id);
CREATE INDEX idx_voucher_programs_category_id ON voucher_programs(category_id);
CREATE INDEX idx_vpb_program_id ON voucher_program_branches(program_id);
CREATE INDEX idx_voucher_program_images_program_id ON voucher_program_images(program_id);
CREATE UNIQUE INDEX uq_voucher_program_primary_image ON voucher_program_images(program_id) WHERE is_primary = TRUE;
CREATE INDEX idx_vpb_branch_id ON voucher_program_branches(branch_id);
CREATE INDEX idx_var_program_id ON voucher_approval_requests(program_id);
CREATE INDEX idx_var_admin_id ON voucher_approval_requests(admin_id);
CREATE INDEX idx_cart_items_customer_id ON cart_items(customer_id);
CREATE INDEX idx_cart_items_program_id ON cart_items(program_id);
CREATE INDEX idx_orders_buyer_user_id ON orders(buyer_user_id);
CREATE INDEX idx_orders_recipient_user_id ON orders(recipient_user_id);
CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE INDEX idx_order_items_program_id ON order_items(program_id);
CREATE INDEX idx_issued_vouchers_program_id ON issued_vouchers(program_id);
CREATE INDEX idx_issued_vouchers_order_item_id ON issued_vouchers(order_item_id);
CREATE INDEX idx_issued_vouchers_owner_user_id ON issued_vouchers(owner_user_id);
CREATE INDEX idx_reviews_feedback_issued_voucher_id ON reviews_feedback(issued_voucher_id);
CREATE INDEX idx_reviews_feedback_customer_id ON reviews_feedback(customer_id);
CREATE INDEX idx_order_cancellations_admin_id ON order_cancellations(admin_id);
CREATE INDEX idx_system_logs_user_id ON system_logs(user_id);
CREATE INDEX idx_banners_program_id ON banners(program_id);
CREATE INDEX idx_popups_program_id ON popups(program_id);
CREATE INDEX idx_contents_program_id ON contents(program_id);

-- Indexes theo truy vấn nghiệp vụ (Business Query Indexes)
CREATE INDEX idx_voucher_programs_display_sale ON voucher_programs(display_status, sale_start_at, sale_end_at);
CREATE INDEX idx_issued_vouchers_owner_status_expires ON issued_vouchers(owner_user_id, usage_status, expires_at);
CREATE INDEX idx_orders_buyer_created ON orders(buyer_user_id, created_at);
CREATE INDEX idx_reviews_feedback_customer_submitted ON reviews_feedback(customer_id, submitted_at);
CREATE INDEX idx_system_logs_user_performed ON system_logs(user_id, performed_at);
