@startuml
left to right direction

actor "Khách hàng" as Customer

rectangle "Hệ thống quản lý voucher" {

    usecase "SR-CUS-05\nQuản lý giỏ hàng" as UC05
    usecase "SR-CUS-06\nTạo đơn hàng" as UC06
    usecase "SR-CUS-07\nNhận voucher\nđã mua" as UC07
    usecase "SR-CUS-08\nĐánh giá và\nphản hồi" as UC08
}

Customer --> UC05
Customer --> UC06
Customer --> UC07
Customer --> UC08

UC06 ..> UC05 : <<extend>>
UC08 ..> UC07 : <<extend>>

@enduml