@startuml
title Đăng xuất (BR-CUS-01)

autonumber
actor "Khách hàng" as KH
boundary "Giao diện" as UI

KH -> UI : clickLogout()
activate UI
UI -> UI : clearLocalToken()
UI --> KH : redirectToHomePage()
deactivate UI
@enduml
