import {
  Activity, ArrowLeft, ArrowRight, Badge, BadgeCheck, Ban, Banknote,
  BarChart3, Bell, Bug, CalendarDays, Camera, Check, CheckCircle, ChevronDown,
  ChevronLeft, ChevronRight, ChevronUp, CircleAlert, CircleHelp, CircleX, ClipboardCheck,
  Clock, CreditCard, Database, Download, Edit, FileImage, FilePlus, FileSearch, FileText,
  FilterX, Flashlight, Gavel, Gift, History, Image, Info, KeyRound, Layers, LayoutDashboard,
  LayoutGrid, Link, List, ListOrdered, Loader2, Lock, LockOpen, LogIn, LogOut, Mail, MapPin, Menu,
  MessageSquare, MoreVertical, Package, PauseCircle, Pencil, Phone, PieChart, PlayCircle, Plus, QrCode,
  Redo, RefreshCw, Save, Search, SearchX, Send, Settings, Share2, Shield,
  ShieldCheck, ShoppingBag, ShoppingCart, Sparkles, Store, Tags, Ticket, Trash2, TrendingDown,
  TrendingUp, Undo, User, Users, View, WalletCards, X, type LucideIcon,
} from "lucide-react";

interface IconProps {
  name: string;
  className?: string;
}

const ICONS: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  database: Database,
  storage: Database,
  group: Users,
  shopping_cart: ShoppingCart,
  shopping_bag: ShoppingBag,
  article: FileText,
  confirmation_number: Ticket,
  qr_code_scanner: QrCode,
  qr_code_2: QrCode,
  analytics: BarChart3,
  bar_chart: BarChart3,
  logout: LogOut,
  login: LogIn,
  search: Search,
  search_off: SearchX,
  notifications: Bell,
  add: Plus,
  payments: Banknote,
  redeem: Gift,
  pie_chart: PieChart,
  donut_large: PieChart,
  trending_up: TrendingUp,
  trending_down: TrendingDown,
  arrow_forward: ArrowRight,
  arrow_back: ArrowLeft,
  check: Check,
  check_circle: CheckCircle,
  task_alt: ClipboardCheck,
  error: CircleX,
  warning: CircleAlert,
  info: Info,
  help_outline: CircleHelp,
  bug_report: Bug,
  mail: Mail,
  email: Mail,
  sms: MessageSquare,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  expand_more: ChevronDown,
  expand_less: ChevronUp,
  more_vert: MoreVertical,
  image: Image,
  add_photo_alternate: FileImage,
  picture_as_pdf: FileText,
  visibility: View,
  share: Share2,
  download: Download,
  person: User,
  store: Store,
  storefront: Store,
  domain: Store,
  location_city: Store,
  location_on: MapPin,
  security: Shield,
  shield: Shield,
  verified_user: ShieldCheck,
  keyboard: CreditCard,
  flashlight_on: Flashlight,
  camera: Camera,
  flip_camera_ios: RefreshCw,
  vpn_key: KeyRound,
  local_cafe: Gift,
  history: History,
  tag: Tags,
  update: RefreshCw,
  refresh: RefreshCw,
  sync: RefreshCw,
  progress_activity: Loader2,
  loader: Loader2,
  spinner: Loader2,
  send: Send,
  close: X,
  cancel: CircleX,
  block: Ban,
  calendar_today: CalendarDays,
  date_range: CalendarDays,
  badge: Badge,
  card_giftcard: Gift,
  delete: Trash2,
  edit: Edit,
  edit_note: Pencil,
  filter_alt_off: FilterX,
  find_in_page: FileSearch,
  folder_open: FileText,
  format_list_bulleted: List,
  format_list_numbered: ListOrdered,
  gavel: Gavel,
  hourglass_top: Activity,
  inventory_2: Package,
  link: Link,
  lock: Lock,
  lock_open: LockOpen,
  menu: Menu,
  post_add: FilePlus,
  published_with_changes: BadgeCheck,
  redo: Redo,
  save: Save,
  settings_suggest: Settings,
  undo: Undo,
  role: WalletCards,
  category: LayoutGrid,
  view_carousel: Layers,
  featured_seasonal: Sparkles,
  pause_circle: PauseCircle,
  play_circle: PlayCircle,
  phone: Phone,
  schedule: Clock,
  timer: Clock,
};

export default function Icon({ name, className = "" }: IconProps) {
  const Component = ICONS[name] ?? CircleHelp;
  const hasExplicitSize = /\b(w-|h-)/.test(className);
  const sizeClasses = hasExplicitSize ? "" : "w-[1em] h-[1em]";

  return (
    <Component
      aria-hidden="true"
      className={`${sizeClasses} inline-block shrink-0 align-middle ${className}`.trim()}
    />
  );
}
