"use client";

import React from "react";
import {
  LayoutDashboard,
  Users,
  User,
  UserPlus,
  UserX,
  Store,
  Building2,
  Ticket,
  ShoppingCart,
  ShoppingBag,
  FileText,
  History,
  RotateCcw,
  LogOut,
  Menu,
  X,
  Bell,
  CreditCard,
  Search,
  Filter,
  FilterX,
  Plus,
  PlusCircle,
  Edit,
  FileEdit,
  Trash2,
  AlertTriangle,
  AlertCircle,
  Check,
  CheckCircle2,
  ShieldCheck,
  ChevronRight,
  ChevronLeft,
  ArrowLeft,
  ArrowRight,
  Download,
  Eye,
  EyeOff,
  Mail,
  Phone,
  MapPin,
  FolderOpen,
  IdCard,
  Save,
  Settings,
  Lock,
  Unlock,
  Shield,
  Sliders,
  Info,
  Image as ImageIcon,
  ImagePlus,
  Calendar,
  Tag,
  ArrowUp,
  ArrowDown,
  TrendingUp,
  TrendingDown,
  Layers,
  Grid,
  MoreVertical,
  MoreHorizontal,
  Copy,
  Clock,
  HelpCircle,
  Sparkles,
  Award,
  BarChart2,
  PieChart,
  DollarSign,
  Briefcase,
  Ban,
  XCircle,
  Gift,
  RefreshCw,
  Link,
  Upload,
  Star,
  List,
  ToggleRight,
  ToggleLeft,
  ChevronDown,
  ChevronUp,
  File,
  Folder,
  ShieldAlert,
  Send,
  LucideIcon,
} from "lucide-react";

// Comprehensive mapping of Material Symbols icon names to Lucide SVG components
const iconMap: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  group: Users,
  groups: Users,
  person: User,
  person_add: UserPlus,
  person_off: UserX,
  store: Store,
  storefront: Store,
  domain: Building2,
  confirmation_number: Ticket,
  ticket: Ticket,
  shopping_cart: ShoppingCart,
  shopping_bag: ShoppingBag,
  history: History,
  history_edu: History,
  published_with_changes: RotateCcw,
  rotate_ccw: RotateCcw,
  restart_alt: RotateCcw,
  filter_list: Filter,
  filter_alt_off: FilterX,
  filter_x: FilterX,
  reset: RotateCcw,
  logout: LogOut,
  menu: Menu,
  close: X,
  notifications: Bell,
  payments: CreditCard,
  credit_card: CreditCard,
  attach_money: DollarSign,
  search: Search,
  add: Plus,
  add_circle: PlusCircle,
  edit: Edit,
  edit_note: FileEdit,
  delete: Trash2,
  delete_forever: Trash2,
  warning: AlertTriangle,
  error: AlertCircle,
  check: Check,
  check_circle: CheckCircle2,
  verified_user: ShieldCheck,
  chevron_right: ChevronRight,
  chevron_left: ChevronLeft,
  chevron_down: ChevronDown,
  chevron_up: ChevronUp,
  expand_more: ChevronDown,
  expand_less: ChevronUp,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  download: Download,
  file_download: Download,
  visibility: Eye,
  visibility_off: EyeOff,
  mail: Mail,
  email: Mail,
  phone: Phone,
  location_on: MapPin,
  folder_open: FolderOpen,
  folder: Folder,
  file: File,
  badge: IdCard,
  save: Save,
  settings_suggest: Settings,
  settings: Settings,
  lock: Lock,
  lock_open: Unlock,
  unlock: Unlock,
  lock_reset: Lock,
  security: Shield,
  shield: Shield,
  shield_alert: ShieldAlert,
  tune: Sliders,
  sliders: Sliders,
  info: Info,
  image: ImageIcon,
  add_photo_alternate: ImagePlus,
  calendar_today: Calendar,
  tag: Tag,
  arrow_upward: ArrowUp,
  arrow_downward: ArrowDown,
  trending_up: TrendingUp,
  trending_down: TrendingDown,
  layers: Layers,
  grid_view: Grid,
  more_vert: MoreVertical,
  more_horiz: MoreHorizontal,
  copy: Copy,
  file_copy: Copy,
  schedule: Clock,
  time: Clock,
  help: HelpCircle,
  sparkles: Sparkles,
  award: Award,
  bar_chart: BarChart2,
  pie_chart: PieChart,
  briefcase: Briefcase,
  block: Ban,
  cancel: XCircle,
  card_giftcard: Gift,
  gift: Gift,
  refresh: RefreshCw,
  sync: RefreshCw,
  autorenew: RefreshCw,
  link: Link,
  upload: Upload,
  cloud_upload: Upload,
  star: Star,
  list: List,
  view_list: List,
  toggle_on: ToggleRight,
  toggle_off: ToggleLeft,
  send: Send,
};

interface IconProps extends React.SVGProps<SVGSVGElement> {
  name: string;
  size?: number | string;
  className?: string;
}

export default function Icon({ name, size, className = "", ...props }: IconProps) {
  if (!name) return null;
  const cleanName = name.trim().toLowerCase();
  const Component = iconMap[cleanName] || HelpCircle;

  return (
    <Component
      className={`inline-block shrink-0 align-middle ${className}`}
      size={size || "1em"}
      {...props}
    />
  );
}
