@startuml
left to right direction

actor "Khách hàng" as Customer

rectangle "Quản lý tài khoản, Tra cứu & Mua Voucher" {

    usecase "Đăng ký tài khoản" as UC01
    usecase "Đăng nhập và quản lý hồ sơ" as UC02
    usecase "Tìm kiếm voucher" as UC03
    usecase "Xem chi tiết voucher" as UC04

    usecase "Quản lý giỏ hàng" as UC05
    usecase "Tạo đơn hàng" as UC06
    usecase "Nhận Voucher" as UC07
    usecase "Đánh giá & phản hồi" as UC08

}

Customer --> UC01
Customer --> UC02
Customer --> UC03
Customer --> UC04
Customer --> UC05
Customer --> UC06
Customer --> UC07
Customer --> UC08

' Business --> UC01
' Business --> UC02
' Business --> UC03
' Business --> UC04
' Business --> UC05
' Business --> UC06
' Business --> UC07
' Business --> UC08

@enduml
