@startuml
left to right direction

actor "Khách hàng" as Customer

rectangle "Quản lý bán Voucher" {

    usecase "Quản lý\ngiỏ hàng" as UC05
    usecase "Tạo\nđơn hàng" as UC06
    usecase "Nhận\nVoucher" as UC07
    usecase "Đánh giá\n& phản hồi" as UC08

}

Customer --> UC05
Customer --> UC06
Customer --> UC07
Customer --> UC08

@enduml