export const COUNTRIES = [
  "Afghanistan",
  "Ai Cập (Egypt)",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Anh Quốc (UK)",
  "Antigua và Barbuda",
  "Ả Rập Xê Út (Saudi Arabia)",
  "Argentina",
  "Armenia",
  "Áo (Austria)",
  "Úc (Australia)",
  "Azerbaijan",
  "Ba Lan (Poland)",
  "Bắc Macedonia",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus (Bêlarút)",
  "Belize",
  "Benin",
  "Bhutan",
  "Bỉ (Belgium)",
  "Bờ Biển Ngà (Côte d'Ivoire)",
  "Bồ Đào Nha (Portugal)",
  "Bolivia",
  "Bosnia và Herzegovina",
  "Botswana",
  "Brazil (Brasil)",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Các Tiểu vương quốc Ả Rập Thống nhất (UAE)",
  "Cameroon",
  "Campuchia (Cambodia)",
  "Canada",
  "Chad",
  "Chile",
  "Colombia",
  "Comoros",
  "Congo",
  "Cộng hòa Dominica",
  "Cộng hòa Séc (Czechia)",
  "Cộng hòa Trung Phi",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Đài Loan (Taiwan)",
  "Đan Mạch (Denmark)",
  "Djibouti",
  "Dominica",
  "Đông Timor (Timor-Leste)",
  "Đức (Germany)",
  "Ecuador",
  "El Salvador",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Gabon",
  "Gambia",
  "Ghana",
  "Grenada",
  "Gruzia (Georgia)",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guinea Xích Đạo",
  "Guyana",
  "Hà Lan (Netherlands)",
  "Haiti",
  "Hàn Quốc (South Korea)",
  "Hoa Kỳ (USA)",
  "Honduras",
  "Hungary",
  "Hy Lạp (Greece)",
  "Iceland",
  "Ấn Độ (India)",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Ý (Italy)",
  "Jamaica",
  "Nhật Bản (Japan)",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Lào (Laos)",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mông Cổ (Mongolia)",
  "Montenegro",
  "Morocco (Ma-rốc)",
  "Mozambique",
  "Myanmar (Miến Điện)",
  "Na Uy (Norway)",
  "Nam Phi (South Africa)",
  "Nam Sudan",
  "Namibia",
  "Nauru",
  "Nepal",
  "New Zealand",
  "Nga (Russia)",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Phần Lan (Finland)",
  "Pháp (France)",
  "Philippines",
  "Qatar",
  "Quần đảo Marshall",
  "Quần đảo Solomon",
  "Romania",
  "Rwanda",
  "Saint Kitts và Nevis",
  "Saint Lucia",
  "Saint Vincent và Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome và Principe",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Síp (Cyprus)",
  "Slovakia",
  "Slovenia",
  "Somalia",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Tây Ban Nha (Spain)",
  "Thái Lan (Thailand)",
  "Thành Vatican",
  "Thổ Nhĩ Kỳ (Turkey)",
  "Thụy Điển (Sweden)",
  "Thụy Sĩ (Switzerland)",
  "Togo",
  "Tonga",
  "Triều Tiên (North Korea)",
  "Trinidad và Tobago",
  "Trung Quốc (China)",
  "Tunisia",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Việt Nam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];
